### ISSUE TITLE
Undefined array key "error" in login page

### ISSUE THREAD

**Issue by Worive** [Emeset-mvc/emeset-app#1]
No es verifica si la sessió `$error` existeix abans de recuperar

# Solutions:
Fer que `Emeset/Request` retorni per deffecte un `null `si no troba una variable de sessió

**Comment by daniprados** [comment]
Solucionat amb la versió 0.1.9 del Framework Emeset.

Ara l'objecte \Emeste\Request torna null quan s'intenta recuperar un valor que no està definit.
