### ISSUE TITLE
Limitació amb la codificació de caràcters

### ISSUE THREAD

**Issue by joanpaneque** [Emeset-mvc/emeset-app#2]
Quan s'utilitzen caràcters amb accents com a resposta del JSON, aquests es converteixen en el codi unicode del caràcter, m'agradaria que es veiés la lletra 'é' i no '\u00e9'

Codi que provoca el problema:
![image](https://github.com/Emeset-mvc/emeset-app/assets/85831928/98feb39f-70ee-47d0-94f4-996c3d3df758)

El problema:
![image](https://github.com/Emeset-mvc/emeset-app/assets/85831928/e1039219-bc90-493e-93ed-c5acf30fa255)

**Comment by daniprados** [comment]
És la codificació que utilitza json_encode dels caràcters especials.
